sonar.projectKey=alrettondini_ES2_2025-2_Habitica
sonar.organization=alrettondini

sonar.sources=website/server,website/client/src,website/common

sonar.exclusions=\
  **/node_modules/**,\
  **/coverage/**,\
  **/dist/**,\
  **/dist-client/**,\
  website/build/**,\
  content_cache/**,\
  i18n_cache/**,\
  website/client/public/static/**,\
  website/raw_sprites/**,\
  apidoc/**,\
  gulp/**,\
  migrations/**,\
  scripts/**,\
  database_reports/**,\
  **/*.min.js,\
  **/*.map

sonar.tests=\
  test,\
  website/client/tests

sonar.coverage.exclusions=\
  test/**,\
  website/client/tests/**,\
  **/*.spec.js,\
  **/*.test.js