sonar.projectKey=alrettondini_ES2_2025-2_Habitica
sonar.organization=alrettondini


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=ES2_2025-2_Habitica
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/node_modules/**,\
  **/coverage/**,\
  **/dist/**,\
  **/dist-client/**,\
  website/build/**,\
  content_cache/**,\
  i18n_cache/**,\
  website/client/public/static/**,\
  website/raw_sprites/**,\
  apidoc/**,\
  gulp/**,\
  migrations/**,\
  scripts/**,\
  database_reports/**,\
  **/*.min.js,\
  **/*.map

sonar.tests=\
  test,\
  website/client/tests

sonar.coverage.exclusions=\
  test/**,\
  website/client/tests/**,\
  **/*.spec.js,\
  **/*.test.js